name: Publish NPM Package

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # 拉取最近两次提交以便于比较

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Get package version
        id: get_version
        run: echo "::set-output name=PKG_VERSION::$(node -p \"require('./package.json').version\")"

      - name: Check if version exists on npm
        id: check_version
        run: |
          VERSION_EXISTS=$(npm view ${{ steps.get_version.outputs.PKG_VERSION }} dist-tags.latest --silent 2>/dev/null)
          if [ -z "$VERSION_EXISTS" ] || [ "$VERSION_EXISTS" != "${{ steps.get_version.outputs.PKG_VERSION }}" ]; then
            echo "::set-output name=should_publish::true"
          else
            echo "::set-output name=should_publish::false"
          fi

      - name: Install dependencies
        if: steps.check_version.outputs.should_publish == 'true'
        run: npm ci

      - name: Publish package
        if: steps.check_version.outputs.should_publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
